"""empty message

Revision ID: 6f250cc4df42
Revises: 4e925d3c7dd4
Create Date: 2025-01-13 22:48:37.901383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f250cc4df42'
down_revision: Union[str, None] = '4e925d3c7dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booked',
    sa.Column('useremail', sa.String(length=30), nullable=False),
    sa.Column('payment', sa.Enum('paid', 'unpaid', name='payment_status'), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('useremail', 'check_out')
    )
    op.create_table('rooms',
    sa.Column('roomid', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('booked', 'vacant', name='enum_options'), nullable=False),
    sa.PrimaryKeyConstraint('roomid')
    )
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('rooms')
    op.drop_table('booked')
    # ### end Alembic commands ###
